### ISSUE TITLE
circleci_domain parameter doesn't seem to work

### ISSUE THREAD

**Issue by jratliff79** [CircleCI-Public/continuation-orb#22]
## Orb version:

0.2.0

## What happened:
We're trying to use this in our self hosted cci setup (3.3.1), however when we attempt to use 

circleci_domain: circleci.ourdomain.com, we get the following error.

```
Error calling workflow: 'setup'
Error calling job: 'setup'
Error calling command: 'continuation/continue'
Unexpected argument(s): circleci_domain

```
## Expected behavior:
It should find that parameter and use it.

**Comment by Markl121** [comment]
Hello @jratliff79! We verified that the `circleci_domain` parameter is accepted in the public registry version `0.2.0`. Would you mind verifying that the local orb registry is in sync with the public registry as per:
https://circleci.com/docs/server-3-operator-orbs/

**Comment by Markl121** [comment]
I will close this issue for now since it has been 2 weeks, please feel free to re-open the issue if the above steps do not work 😄
