### ISSUE TITLE
Continue script is not working on alpine image (using sh)

### ISSUE THREAD

**Issue by TimoPtr** [CircleCI-Public/continuation-orb#23]
## Orb version:

0.2.0

## What happened:

 When invoking the command continue on an alpine instance it fail with `/bin/sh: syntax error: unexpected redirection`

## Expected behavior:

Working in the same way as on any other linux distribution that use bash.

## Additional Information:

The issue is because of the syntax used in the continue.sh script.

I'm going to open a PR to fix the issue

**Comment by felicianotech** [comment]
> Working in the same way as on any other linux distribution that use bash.

Alpine doesn't use bash.

**Comment by Fernando-Abreu** [comment]
This was fixed in #24
